index/urls.py
from django.urls import path

from . import views
from .views import Get404View

urlpatterns = [
    path('', views.home, name='index-home'),
    path('404/', Get404View.as_view(), name='index-404'),
]

medigal/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('index.urls')),
    path('contacts/', include('contacts.urls')),
    path('doctors/', include('doctors.urls')),
    path('applicants/', include('applicants.urls')),
    path('company/', include('company.urls')),
    path('scheduling/', include('scheduling.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

scheduling/urls.py
from django.urls import path

from .views import NewAppointmentView, AppointmentView, AppointmentListView

urlpatterns = [
    path('', AppointmentListView.as_view(), name='appointment_list'),
    path('new-appointment/', NewAppointmentView.as_view(), name='new_appointment'),
    path('appointment/<int:pk>/', AppointmentView.as_view(), name='appointment'),
]

scheduling/models.py
from django.urls import reverse
from django.utils import timezone
from django.db import models

from applicants.models import Applicant
from doctors.models import Doctor
from users.models import User


class Appointment(models.Model):
    INITIAL = 'Initial'
    RE_EVAL = 'Re-evaluation'
    RESCHEDULED = 'Reschedued'
    APPOINTMENT_TYPE = [
        (INITIAL, 'Initial'),
        (RE_EVAL, 'Re-evaluation'),
        (RESCHEDULED, 'Rescheduled')
    ]

    AME = 'AME'
    QME = 'QME'
    EXAM_TYPE = [
        (QME, 'QME'),
        (AME, 'AME'),
    ]

    # Using init for saving datetimefields on UpdateView
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.b_records_sent = self.records_sent
        self.b_records_received = self.records_received

    appointment_type = models.CharField(max_length=20, choices=APPOINTMENT_TYPE, default=INITIAL)
    exam_type = models.CharField(max_length=120, choices=EXAM_TYPE, default=QME)
    doctor = models.ForeignKey(Doctor, on_delete=models.CASCADE)
    applicant = models.ForeignKey(Applicant, on_delete=models.CASCADE)
    appointment_date = models.DateTimeField()
    panel_number = models.CharField(max_length=120, blank=True, null=True)

    scheduled_by = models.ForeignKey(User, on_delete=models.PROTECT)
    scheduled_date = models.DateTimeField(auto_now_add=True)

    records_sent = models.BooleanField(default=False)
    # datetimefields require null or else integrityerror when using blank=True
    records_sent_date = models.DateTimeField(blank=True, null=True)

    records_received = models.BooleanField(default=False)
    records_received_date = models.DateTimeField(blank=True, null=True)

    notes = models.TextField(blank=True)

    # Following fields will be hidden from initial create view and displayed on updateview once applicant has attended or missed appt.
    # For attended, keep default None or else default = "didn't attend"
    # LOGIC: If appointment date, show:
    attended = models.BooleanField(blank=True, null=True)

    """ Set rescheduled = True if the current object has been rescheduled to new date """
    rescheduled = models.BooleanField(default=False)
    
    """
    if didn't attend, set logic:
    create another instance of appt model, 
    input necessary previous data except 
    appt date/attneded will be blank on new object and 
    type=rescheduled
    """

    def get_absolute_url(self):
        return reverse('appointment', kwargs={'pk': self.pk})

scheduling/forms.py
from django import forms
from django.forms import ModelForm
from django.forms.widgets import DateTimeInput

from .models import Appointment


class NewAppointmentForm(ModelForm):
    appointment_date = forms.DateTimeField(
        input_formats = ['%Y-%m-%dT%H:%M'],
        widget = forms.DateTimeInput(
            attrs={
                'type': 'datetime-local'
            },
            format='%Y-%m-%dT%H:%M'
        )
    )

    class Meta:
        model = Appointment
        fields = ['appointment_type', 'exam_type', 'applicant', 'doctor', 'appointment_date', 'panel_number']
        # widgets = {
        #     'appointment_date': DateTimeInput(attrs={
        #         'type': 'datetime-local'
        #     }),
        # }
        

scheduling/views.py
from datetime import datetime

from django.contrib import messages
from django.views.generic import ListView, DetailView, UpdateView
from django.views.generic.edit import CreateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.shortcuts import get_object_or_404
from django.forms.widgets import DateTimeInput
from django.shortcuts import render, redirect
from django.utils import timezone

from applicants.models import Applicant
from doctors.models import Doctor
from contacts.models import Address, Telephone, Email
from users.models import User
from .models import Appointment
from .forms import NewAppointmentForm

class NewAppointmentView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    model = Appointment
    template_name = 'scheduling/new_appointment.html'
    success_message = 'Appointment has been created successfully!'
    form_class = NewAppointmentForm # If using form_class, can't use fields because it's declared in the ModelForm

    def get_form(self, *args, **kwargs):
        #Using get_form because CreateView doesn't have get_queryset
        form = super().get_form(*args, **kwargs)
        form.fields['applicant'].queryset = Applicant.objects.filter(created_by=self.request.user)
        return form

    def form_valid(self, form):
        form.instance.scheduled_by = self.request.user
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Schedule a new medical-legal appointment'
        return context


class AppointmentListView(LoginRequiredMixin, UserPassesTestMixin, SuccessMessageMixin, ListView):
    model = Appointment
    context_object_name = 'appointment'

    def get_queryset(self):
        filter_users = Appointment.objects.filter(scheduled_by=self.request.user)
        filter_order = filter_users.order_by('appointment_date')
        return filter_order

    def test_func(self):
        if self.request.user.is_authenticated:
            return True
        return False

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'View scheduled appointments'
        return context


class AppointmentView(LoginRequiredMixin, UserPassesTestMixin, SuccessMessageMixin, UpdateView):
    model = Appointment
    fields = ['records_sent', 'records_received', 'notes', 'attended']
    template_name = 'scheduling/appointment_view.html'
    success_message = 'Updated successfully!'

    def test_func(self):
        self.appointment = self.get_object()
        if self.request.user.is_staff or self.request.user == self.appointment.scheduled_by:
            return True
        return False

    def form_valid(self, form):
        """ Update sent/received datetimes to current time
        when sent/received is checked from false to true.
        """
        appointment = self.object
        if form.instance.records_sent and appointment.b_records_sent != form.instance.records_sent:
            appointment.records_sent_date = timezone.now()
        if form.instance.records_received and appointment.b_records_received != form.instance.records_received:
            appointment.records_received_date = timezone.now()
        return super().form_valid(form)

scheduling/templates/scheduling/appointment_list.html
{% extends 'index/base.html' %}

{% block breadcrumb %}
    <ol class="breadcrumb"> 
        <li class="breadcrumb-item"><a href="{% url 'index-home' %}">Home</a></li>
        <li class="breadcrumb-item active" aria-current="page">Schedule new appointment</li>
    </ol>
{% endblock %}

{% block row %}
    <div class="row">
        <div class="col">
            {% for app in appointment %}
                {% if not app.attended %}
                    <div>
                        <a href="{% url 'appointment' app.id %}">View</a>
                        {{ app.applicant }}
                        {{ app.appointment_date }}
                    </div>
                {% endif %}
                {% if app.attended %}
                    <div>
                        <h5>Attended appointments:</h5>
                        <a href="{% url 'appointment' app.id %}">View</a>
                        <p><del>
                            {{ app.applicant }}
                            {{ app.appointment_date }}
                        </del></p>
                    </div>
                {% endif %}
            {% endfor %}
        </div>
    </div>
{% endblock %}

scheduling/templates/scheduling/appointment_view.html
{% extends 'index/base.html' %}
{% load tz %}

{% block row %}
<div class="row">

    <div class="col-md-8">
        <h1>{{ object.appointment_type.upper }} {{ object.exam_type }} APPOINTMENT ({{ object.doctor.specialty }})</h1>
        <h3>For {{ object.applicant }}</h3>
        <h4>With {{ object.doctor }} on {{ object.appointment_date }}</h4>

        <p>Location: {{ object.doctor.address.first }}</p>
        <form method="POST">{% csrf_token %}
            <fieldset>
                <div class="form-check">
                    {{ form.records_sent }}
                    <label for="id_records_sent" class="ml-2">Records sent</label>
                    {% if object.records_sent %}
                        on {{ object.records_sent_date }}
                    {% endif %}

                    <hr />
                    {{ form.records_received }}
                    <label for="id_records_received" class="ml-2">Records received</label>
                    {% if object.records_received %}
                        on {{ object.records_received_date }}
                    {% endif %}
                </div>

                <hr />
                <div class="form-group d-flex flex-column">
                    <label for="id_notes">Notes</label>
                    {{ form.notes }}
                </div>

                <hr />
                {% if object.attended %}
                <div class="form-check text-success">
                {% else %}
                <div class="form-check">
                {% endif %}
                <label for="id_attended" class="mr-2">Attended</label>
                {{ form.attended }}
                </div>

                <hr />
                <button class="btn btn-outline-info" type="submit">Save</button>
            </fieldset>
        </form>
    </div>
</div>

{% endblock %}

scheduling/templates/scheduling/new_appointment.html
{% extends 'index/base.html' %}
{% load crispy_forms_tags %}

{% block breadcrumb %}
    <ol class="breadcrumb"> 
        <li class="breadcrumb-item"><a href="{% url 'index-home' %}">Home</a></li>
        <li class="breadcrumb-item active" aria-current="page">Schedule new appointment</li>
    </ol>
{% endblock %}

{% block row %}
<div class="row">
    <div class="col">
        <form method="POST">
            {% csrf_token %}
            <fieldset>
                <legend>Schedule New Appointment</legend>
                {{ form|crispy }}
            <button class="btn btn-outline-info" type="submit">Schedule</button>
            </fieldset>

        </form>
    </div>
</div>
{% endblock %}